### ISSUE TITLE
Doesn't appear to do anything

### ISSUE THREAD

**Issue by timdonovanuk** [michael-genson/Unified-Shopping-List#29]
I'm not sure from the documentation what the functionality of this actually _is_ - but I set it up anyway successfully. I added a new item to mealie, and also a new item into Alexa, but neither syncs to the other system. Thanks anyway!

**Comment by michael-genson** [comment]
Hey there! Did you map your shopping lists?

https://shopping-lists.genson.dev/app/map-shopping-lists

Nothing will sync until you connect your Mealie shopping list to your Alexa shopping list. After that, you should see them stay in sync

**Comment by timdonovanuk** [comment]
Hi :)

Yep I sure did:

![image](https://github.com/michael-genson/Unified-Shopping-List/assets/8156439/eaaf8a39-e63d-4e8d-a060-c88c7bf4169e)

Added this item in Mealie but it never appears on my Alexa list. And tried vice-versa with no luck:

![image](https://github.com/michael-genson/Unified-Shopping-List/assets/8156439/3cdc195e-10f4-4921-b6ea-2f0fcf1cea87)

**Comment by michael-genson** [comment]
Awesome, you did everything right then. Can you confirm your Mealie version and build? It should be under site settings (bottom left of the sidebar, or just go to `https://your-url.tld/admin/site-settings`)

**Comment by timdonovanuk** [comment]
Cool :D 

Yep sure:

Version
nightly

Build
[bdf6b1054ece531276c62ca7d4f0ee718bfd2efb](https://github.com/hay-kot/mealie/commit/bdf6b1054ece531276c62ca7d4f0ee718bfd2efb)

I see now there is an actual 1.x version (v1.0.0-RC2) - I'll try switching to that one! In my defence, my mealie reports that it's up to date!

**Comment by michael-genson** [comment]
Ah yep, that might do it. USL supported the old nightly/omni-nightly versions previously, but I think I added some breaking changes lately since Mealie added a bunch of support for food searching. Once Mealie has a true 1.0.0 release I will officially support that indefinitely, even if there are new features to leverage in the future.

FYI, on the version differences: https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/#migrating-from-other-v1-versions

The reason you were seeing that you were on latest was because Mealie switched from dockerhub to ghcr. If you update your Mealie instance to RC2 or nightly you should be in good shape. The new ghcr RC builds only have one container now, so you don't need a frontend and backend, which is super nice.

**Comment by michael-genson** [comment]
Hey there, just wanted to follow-up - were you able to get this working with the newest version of Mealie?
Now that Mealie has an official v1 release, we will support that indefinitely, as well as the "latest" version.

**Comment by michael-genson** [comment]
Closing this since the app seems to be working as expected. If you're still experiencing issues, feel free to re-open
